/**
 * Expo config plugin: enable Android core library desugaring.
 *
 * WHY THIS EXISTS AS A PLUGIN, NOT A HAND EDIT
 * --------------------------------------------
 * `android/` is gitignored and regenerated by `expo prebuild`. Anything edited
 * directly in android/app/build.gradle survives until the next prebuild and
 * then silently disappears, taking the build with it. Encoding the change here
 * means it is reapplied every time the folder is generated.
 *
 * WHY DESUGARING
 * --------------
 * The Google Navigation SDK requires `coreLibraryDesugaringEnabled` to be true
 * regardless of minSdkVersion — it uses java.time / java.nio APIs that do not
 * exist on older Android runtimes, and desugaring back-ports them. Without it
 * the build fails at dex time with missing-class errors that do not obviously
 * point at this cause.
 *
 * The `_nio` variant of desugar_jdk_libs is the one Google's own documentation
 * specifies for the Navigation SDK; the plain variant omits the NIO back-ports
 * the SDK relies on.
 */
const { withAppBuildGradle } = require('@expo/config-plugins');

const DESUGAR_DEP = "com.android.tools:desugar_jdk_libs_nio:2.0.4";

/** Insert `compileOptions { coreLibraryDesugaringEnabled true }` into `android { }`. */
function addCompileOptions(src) {
  // Already handled — prebuild runs repeatedly, so this must be idempotent.
  if (src.includes('coreLibraryDesugaringEnabled')) return src;

  if (src.includes('compileOptions {')) {
    // A compileOptions block exists; add the flag as its first entry.
    return src.replace(
      'compileOptions {',
      'compileOptions {\n        coreLibraryDesugaringEnabled true'
    );
  }

  // No compileOptions block — create one immediately inside `android {`.
  const anchor = /^android\s*\{/m;
  if (!anchor.test(src)) {
    throw new Error(
      '[withCoreLibraryDesugaring] Could not find the `android {` block in ' +
        'android/app/build.gradle. Refusing to guess — the Navigation SDK ' +
        'will fail at dex time without desugaring, so this must not fail quietly.'
    );
  }
  return src.replace(
    anchor,
    'android {\n    compileOptions {\n        coreLibraryDesugaringEnabled true\n    }\n'
  );
}

/** Add the desugar_jdk_libs artifact to the app's `dependencies { }`. */
function addDesugarDependency(src) {
  if (src.includes('desugar_jdk_libs')) return src;

  const anchor = /^dependencies\s*\{/m;
  if (!anchor.test(src)) {
    throw new Error(
      '[withCoreLibraryDesugaring] Could not find the `dependencies {` block ' +
        'in android/app/build.gradle.'
    );
  }
  return src.replace(
    anchor,
    `dependencies {\n    coreLibraryDesugaring '${DESUGAR_DEP}'\n`
  );
}

module.exports = function withCoreLibraryDesugaring(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error(
        '[withCoreLibraryDesugaring] Expected a Groovy build.gradle, got ' +
          `"${cfg.modResults.language}". Not patching blindly.`
      );
    }
    let src = cfg.modResults.contents;
    src = addCompileOptions(src);
    src = addDesugarDependency(src);
    cfg.modResults.contents = src;
    return cfg;
  });
};
